### ISSUE TITLE
mp4素材播放报错 Failed to execute 'decode' on 'VideoDecoder': A key frame is required after configure() or flush() 

### ISSUE THREAD

**Issue by 23233** [bilibili/WebAV#206]
### 复现步骤
* 打开官网剪辑demo https://bilibili.github.io/WebAV/demo/6_4-video-editor
* 选择本地视频 选择此视频 
[零日攻擊 60s.zip](https://github.com/user-attachments/files/16373055/60s.zip)
* 播放几秒后开始报错

### 错误提示
![image](https://github.com/user-attachments/assets/44c58df5-0f44-4194-8f92-2df4383a7075)

**Comment by awakeyue** [comment]
我也遇到了

**Comment by Yukiniro** [comment]
WebAV 的解封装依赖于 mp4box.js，这个素材在 mp4box.js 中获取的关键帧索引跟 ffmpeg 获取的关键帧索引数据不一致
mp4box.js 的关键帧索引数据(前 3 个关键帧)为：0, 51, 102
ffmpeg     的关键帧索引数据(前 5 个关键帧)为：0, 1, 25, 52, 103 
所以在播放过程中使用 51 进行 `dec.decode(chunks[i]);` 时会抛出异常：`Failed to execute 'decode' on 'VideoDecoder': A key frame is required after configure() or flush().`

**Comment by hughfenghen** [comment]
原因是该视频中标记为 is_sync 的 sample 是一个普通 I 帧，非 IDR 帧；
当前解码策略是按 GoP 分组（以 I 帧分割组）解码，每次解码后会 flush；
而 WebCodecs 要求 flush 后的第一帧必须为 IDR 帧，所以会报错。

修改解码策略，以 IDR 帧分组， 且移除 IDR 帧前面的 SEI 信息，解决报错。

**Comment by hughfenghen** [comment]
另外，视频文件的音频编码（ec-3）是 WebCodecs 不支持的格式，所以播放不会有声音。

**Comment by yingersun** [comment]
I encountered "First sample not idr frame" warning in console. And I believe it's because I am fetching a 9:16 iphone video as the MP4Clip. 

I tested with one 9:16 video and it gave the "First sample not idr frame" error.

I tested with a second 9:16 different video and it couldn't add to timeline (using video editor demo) and gave this error "Uncaught (in promise) Error: MP4Clip stream is done, but not emit ready" in console.
